# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b78b91b24bd05f032ad84a49f283b3c469b6683c9021c97a41799acdcc5257aea7f62ec92e65beead6d033517c91ab0d035485f39cbbf43c85ca61686435132a

test:
  secret_key_base: a9443fc643543930a328d10ae53076cccf0fb314286b66ba5793e2a47161ae1e94a99be06b1473e88be397dc51a66f89e77b007a9e9836588bc858b5bd103850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
